### PR TITLE
Add missing functions from Pixbuf

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by gkoz** [comment]
I'm about to push the refactored gdk...

**Comment by GuillaumeGomez** [comment]
Then do, I'll merge it later !

**Comment by GuillaumeGomez** [comment]
Crap, I thought we asked about import `std` instead of `std::ptr`. Let's say we didn't see anything.

**Comment by GuillaumeGomez** [comment]
@gkoz: On this one, I don't agree with you. I think `to_glib` and `from_glib` are too general.

**Comment by GuillaumeGomez** [comment]
@gkoz: Actually no, that could be nice.

**Pull request merged**
