### PR TITLE
Added keyval_to_unicode

### PR DESCRIPTION
**Pull request by trolleyman**
Very useful function found after a few days digging.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Why did you close it ? It was a nice one !

**Comment by trolleyman** [comment]
Ah sorry, I didn't know you could edit the pull request, thought you had to close and start over... I'm learning though :P

**Comment by gkoz** [comment]
Oh wow, editing on github must be a lot harder than locally.

**Comment by GuillaumeGomez** [comment]
I confirm.

**Pull request closed without merging**
